-- Seed creators, catalog, comments, and a Guard enforcement sample.
insert into profiles (user_id, handle, display_name, bio, avatar_url, is_seed)
values
  ('seed-northline', 'northline', 'Northline', 'Ridges, weather, and the long quiet of the north.', '/avatars/northline.jpg', true),
  ('seed-fieldnotes', 'fieldnotes', 'Field Notes', 'Food, craft, and the small rituals of a kitchen.', '/avatars/fieldnotes.jpg', true),
  ('seed-nightshift', 'nightshift', 'Night Shift', 'Cities after the lights take over.', '/avatars/nightshift.jpg', true),
  ('seed-openroad', 'openroad', 'Open Road', 'Empty miles. Heat. Horizon.', '/avatars/openroad.jpg', true),
  ('seed-atlas', 'atlas', 'Studio Atlas', 'Independent animation and short film.', '/avatars/atlas.jpg', true),
  ('seed-harbor', 'harbor', 'Harbor Light', 'Water, weather, and the edge of the map.', '/avatars/harbor.jpg', true),
  ('seed-quiet', 'quiethours', 'Quiet Hours', 'Rooms, linen, and late morning light.', '/avatars/quiethours.jpg', true),
  ('seed-pulse', 'pulse', 'Pulse', 'The house channel. Safety, product, and originals.', '/avatars/pulse.jpg', true)
on conflict (user_id) do nothing;

insert into videos (id, user_id, title, description, tags, src_url, poster_url, duration_sec, is_short, status, view_count, like_count, comment_count, created_at)
values
  ('v-sintel', 'seed-atlas', 'Sintel',
   'A short film from the Blender Foundation. A young woman, a dragon, and a world cut from stone and sky. CC-BY.',
   'film,animation,fantasy',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/Sintel.jpg',
   888, false, 'published', 4823310, 192004, 2, now() - interval '18 days'),
  ('v-bunny', 'seed-atlas', 'Big Buck Bunny',
   'The Peach Open Movie. A very large rabbit, a very small grievance. CC-BY.',
   'film,animation,comedy',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/BigBuckBunny.jpg',
   596, false, 'published', 9102201, 301442, 2, now() - interval '32 days'),
  ('v-tears', 'seed-atlas', 'Tears of Steel',
   'Live action and visual effects from Amsterdam. Robots, rain, and a city that will not stay in the past. CC-BY.',
   'film,scifi,vfx',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/TearsOfSteel.jpg',
   734, false, 'published', 2210884, 88012, 1, now() - interval '11 days'),
  ('v-elephants', 'seed-atlas', 'Elephants Dream',
   'The first open movie. Two people inside a machine that may be a mind. CC-BY.',
   'film,animation,experimental',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ElephantsDream.jpg',
   654, false, 'published', 1204412, 44190, 1, now() - interval '40 days'),
  ('v-joyrides', 'seed-openroad', 'Joyride, late light',
   'A stretch of tarmac and the last hour of sun. No destination worth naming.',
   'travel,driving,dusk',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerJoyrides.jpg',
   15, false, 'published', 802114, 29110, 1, now() - interval '3 days'),
  ('v-escapes', 'seed-openroad', 'Escapes',
   'Leave the grid. The landscape does the rest.',
   'travel,landscape',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerEscapes.jpg',
   15, false, 'published', 655201, 18840, 0, now() - interval '6 days'),
  ('v-subaru', 'seed-openroad', 'Street and dirt',
   'A car that does not mind which surface you give it. Dust, gravel, then the road again.',
   'travel,motorsport',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/SubaruOutbackOnStreetAndDirt.jpg',
   30, false, 'published', 440128, 12004, 0, now() - interval '9 days'),
  ('v-meltdowns', 'seed-nightshift', 'Meltdown hour',
   'When the city overheats. Glass, signal, and a sky that will not cool.',
   'city,night,editorial',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerMeltdowns.jpg',
   15, false, 'published', 990441, 33012, 1, now() - interval '2 days'),
  ('v-fun', 'seed-quiet', 'For a larger quiet',
   'A short on rooms, color, and staying in.',
   'lifestyle,interior',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerFun.jpg',
   15, false, 'published', 210334, 8801, 0, now() - interval '5 days'),
  ('s-cliff', 'seed-harbor', 'Cliff swell',
   'The Pacific does not ask. Six seconds of impact against volcanic rock.',
   'ocean,nature,drop',
   '/shorts/cliff-swell.mp4',
   '/posters/cliff-swell.jpg',
   6, true, 'published', 2408810, 198440, 2, now() - interval '1 day'),
  ('s-blazes', 'seed-northline', 'High desert firelight',
   'A burn that stays in the bowl of the land. Watch the sky go copper.',
   'desert,night,drop',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerBlazes.jpg',
   15, true, 'published', 1102044, 77012, 1, now() - interval '20 hours'),
  ('s-joy', 'seed-openroad', 'Center line',
   'Keep the yellow line in the lower third and do not look away.',
   'driving,drop,dusk',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerJoyrides.jpg',
   15, true, 'published', 880120, 54010, 0, now() - interval '8 hours'),
  ('s-escape', 'seed-northline', 'Leave now',
   'A fifteen-second reminder that the map still has empty cells.',
   'travel,drop',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerEscapes.jpg',
   15, true, 'published', 701204, 41008, 0, now() - interval '4 hours'),
  ('s-melt', 'seed-nightshift', 'Signal storm',
   'Vertical crop of a city that will not sleep. Drop, mute, keep going.',
   'city,drop',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerMeltdowns.jpg',
   15, true, 'published', 1560021, 99004, 1, now() - interval '14 hours'),
  ('s-fun', 'seed-quiet', 'Stay in',
   'A small room, a large quiet. Loop it.',
   'lifestyle,drop',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerFun.jpg',
   15, true, 'published', 330120, 18004, 0, now() - interval '2 hours'),
  ('v-removed', 'seed-pulse', 'Removed by Pulse Guard',
   'This title was a policy sample. It never ran in the public feed.',
   'safety',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
   'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerFun.jpg',
   15, false, 'taken_down', 0, 0, 0, now() - interval '12 hours')
on conflict (id) do nothing;

insert into comments (id, video_id, user_id, body, status, created_at)
values
  ('c1', 'v-sintel', 'seed-northline', 'The scale of those landscapes still surprises me.', 'visible', now() - interval '4 days'),
  ('c2', 'v-sintel', 'seed-harbor', 'Watch it once for the story, once for the light.', 'visible', now() - interval '3 days'),
  ('c3', 'v-bunny', 'seed-quiet', 'This is the one I put on when the room needs color.', 'visible', now() - interval '10 days'),
  ('c4', 'v-bunny', 'seed-openroad', 'The butterfly still gets me.', 'visible', now() - interval '8 days'),
  ('c5', 'v-tears', 'seed-nightshift', 'Amsterdam as a character. The rain is doing overtime.', 'visible', now() - interval '2 days'),
  ('c6', 'v-elephants', 'seed-pulse', 'A machine with a memory. Still the strangest open movie.', 'visible', now() - interval '12 days'),
  ('c7', 'v-joyrides', 'seed-harbor', 'That last hour of sun on the hood.', 'visible', now() - interval '1 day'),
  ('c8', 'v-meltdowns', 'seed-atlas', 'The edit is mean in the best way.', 'visible', now() - interval '20 hours'),
  ('c9', 's-cliff', 'seed-northline', 'You can feel the cold off the spray.', 'visible', now() - interval '10 hours'),
  ('c10', 's-cliff', 'seed-quiet', 'Looping this on mute at 1am. No notes.', 'visible', now() - interval '6 hours'),
  ('c11', 's-blazes', 'seed-openroad', 'Copper sky. That is the whole argument.', 'visible', now() - interval '12 hours'),
  ('c12', 's-melt', 'seed-fieldnotes', 'Drop is dangerous. I was here for forty minutes.', 'visible', now() - interval '5 hours')
on conflict (id) do nothing;

insert into follows (follower_id, creator_id)
values
  ('seed-harbor', 'seed-northline'),
  ('seed-quiet', 'seed-fieldnotes'),
  ('seed-nightshift', 'seed-atlas'),
  ('seed-openroad', 'seed-harbor'),
  ('seed-fieldnotes', 'seed-quiet'),
  ('seed-atlas', 'seed-northline')
on conflict do nothing;

insert into moderation_events (id, user_id, video_id, action, category, severity, details, created_at)
values
  ('m1', 'seed-pulse', 'v-removed', 'takedown', 'graphic-violence', 'severe',
   'Pulse Guard removed this sample listing to demonstrate a public takedown. No account was harmed.',
   now() - interval '12 hours')
on conflict (id) do nothing;
