/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShortsRouteImport } from './routes/shorts'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as YouRouteImport } from './routes/you'
import { Route as CHandleRouteImport } from './routes/c.$handle'
import { Route as WatchVideoIdRouteImport } from './routes/watch.$videoId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsRoute = ShortsRouteImport.update({
  id: '/shorts',
  path: '/shorts',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const YouRoute = YouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => rootRouteImport,
} as any)
const CHandleRoute = CHandleRouteImport.update({
  id: '/c/$handle',
  path: '/c/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchVideoIdRoute = WatchVideoIdRouteImport.update({
  id: '/watch/$videoId',
  path: '/watch/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/safety': typeof SafetyRoute
  '/search': typeof SearchRoute
  '/shorts': typeof ShortsRoute
  '/upload': typeof UploadRoute
  '/you': typeof YouRoute
  '/c/$handle': typeof CHandleRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/safety': typeof SafetyRoute
  '/search': typeof SearchRoute
  '/shorts': typeof ShortsRoute
  '/upload': typeof UploadRoute
  '/you': typeof YouRoute
  '/c/$handle': typeof CHandleRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/safety': typeof SafetyRoute
  '/search': typeof SearchRoute
  '/shorts': typeof ShortsRoute
  '/upload': typeof UploadRoute
  '/you': typeof YouRoute
  '/c/$handle': typeof CHandleRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/safety'
    | '/search'
    | '/shorts'
    | '/upload'
    | '/you'
    | '/c/$handle'
    | '/watch/$videoId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/safety'
    | '/search'
    | '/shorts'
    | '/upload'
    | '/you'
    | '/c/$handle'
    | '/watch/$videoId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/safety'
    | '/search'
    | '/shorts'
    | '/upload'
    | '/you'
    | '/c/$handle'
    | '/watch/$videoId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SafetyRoute: typeof SafetyRoute
  SearchRoute: typeof SearchRoute
  ShortsRoute: typeof ShortsRoute
  UploadRoute: typeof UploadRoute
  YouRoute: typeof YouRoute
  CHandleRoute: typeof CHandleRoute
  WatchVideoIdRoute: typeof WatchVideoIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts': {
      id: '/shorts'
      path: '/shorts'
      fullPath: '/shorts'
      preLoaderRoute: typeof ShortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/you': {
      id: '/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof YouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$handle': {
      id: '/c/$handle'
      path: '/c/$handle'
      fullPath: '/c/$handle'
      preLoaderRoute: typeof CHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$videoId': {
      id: '/watch/$videoId'
      path: '/watch/$videoId'
      fullPath: '/watch/$videoId'
      preLoaderRoute: typeof WatchVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SafetyRoute: SafetyRoute,
  SearchRoute: SearchRoute,
  ShortsRoute: ShortsRoute,
  UploadRoute: UploadRoute,
  YouRoute: YouRoute,
  CHandleRoute: CHandleRoute,
  WatchVideoIdRoute: WatchVideoIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
